name: trackizer_demo_app
description: Trackizer is a free subscription tracker app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  beamer: ^1.5.2
  blur: ^3.1.0
  bot_toast: ^4.0.3
  dotted_decoration: ^2.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.7
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  intl: ^0.17.0
  json_annotation: ^4.6.0
  responsive_framework: ^0.2.0
  simple_gradient_text: ^1.2.3
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
  fonts:
    - family: Trackizer Icons
      fonts:
       - asset: assets/fonts/trackizer-icons.ttf

flutter_native_splash:
  color: "#1C1C23"
  image: assets/images/splash-logo.png
  color_dark: "#1C1C23"
  image_dark: assets/images/splash-logo.png
  fullscreen: true
